### ISSUE TITLE
Sanitation

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#10]
Sanitize all modules including their search bars
1. Pawning
2. Client Management
3. Money Transfer
4. Insurance
5. Dollar
6. Branch 2 Branch
7. and Cash In/Out

Check their INPUT FIELDS, SEARCH BARS and Key Binded Fields

**Comment by Blade1992** [comment]
Changes in Dollar: Dynamic Search in CurrencyList form perform keydown or doubleclicking the data 
in listbox

**Comment by Blade1992** [comment]
Enhancement
1. Pawning - add DreadKnight in Searching Data
2. Client Management-add DreadKnight in Searching Data
3. Money Transfer-add DreadKnight in Searching Data
4. Insurance-add DreadKnight in Searching Data
5. Dollar-add DreadKnight in Searching Data
6. Branch 2 Branch-add DreadKnight in Searching Data
7. and Cash In/Out-add DreadKnight in Searching Data

**Comment by cadeath** [comment]
Good

Please check inputs that can be SAVE

**Comment by cadeath** [comment]
Please summary the list of changes for easy checking...
thank you

**Comment by marzxxx90** [comment]
Money Transfer search allow to search sender and receiver
Cash In/out search allow to search case sensitive

**Comment by cadeath** [comment]
I mean, katong mga modules na naEDIT ninyo para dali iCheck

**Comment by cadeath** [comment]
@marzxxx90 @cloudNine09 
please update this

**Comment by marzxxx90** [comment]
unsa ning Key Binded Fields sir ?

**Comment by marzxxx90** [comment]
Pawning 
Client  Management
Money Transfer
Insurance
Money Exchange
Branch To Branch
Cash In/out
Na check na tanan Search Bar, Event key ug input fields ani sir

**Comment by cadeath** [comment]
naUpdate na ni sa 122?

**Comment by marzxxx90** [comment]
na update na sir

**Comment by cadeath** [comment]
Please double check

**Comment by marzxxx90** [comment]
na check na nko sir..dli na maka search ug 3 characters lng ang tanan search sa transaction ..tapos ang client management maka search na ug multiple name pareha sa pawning search

**Comment by cadeath** [comment]
INCLUDED in Version 1.2.2.15 (Master)
