### ISSUE TITLE
Detail OTP Monitoring

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#102]
Records the changes every changes especially on Series

**Comment by marzxxx90** [comment]
Added Remarks field in Table OTP
Record all Series change in Settings and other transaction use OTP
Branch: 13

**Comment by cadeath** [comment]
@cloudNine09 to be checked by JayR

**Comment by marzxxx90** [comment]
Included nani sa Lastest Update

**Comment by cadeath** [comment]
Please attached sample logs please

**Comment by marzxxx90** [comment]
![aa](https://cloud.githubusercontent.com/assets/19383754/24320852/0097c26e-1179-11e7-8a55-b35148a690fb.png)

**Comment by cadeath** [comment]
Add Capability to identify the OLD and new changes

**Comment by marzxxx90** [comment]
![aa](https://cloud.githubusercontent.com/assets/19383754/24538033/448588ae-1619-11e7-81d3-bfa480ff066e.png)
