### ISSUE TITLE
POS Reports

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#112]
To be provided
@marzxxx90

**Comment by cadeath** [comment]
INVENTORY REPORT for a specific date, DONE
not printable STOCK CARD, DONE

**Comment by cadeath** [comment]
Include report

DAILY SALES REPORT

**Comment by cadeath** [comment]
Please produce tomorrow first hour in the morning

**Comment by marzxxx90** [comment]
Added Sales Report
Branch: 1.4-POS Sales Report
Updated from 1.4-POS
