### ISSUE TITLE
User Log

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#114]
Include userID every transactions made

**Comment by Bladier** [comment]
Sir asa ni imong gina mean sa User Logging?

**Comment by cadeath** [comment]
paDouble Check ko para maClose
katong mga transactions sa POS kung nakaRecord ba kung kinsai nagPunch

**Comment by cadeath** [comment]
@marzxxx90 kindly update this if this is to close or not

**Comment by marzxxx90** [comment]
Included nani sa 1.4 POS
