### ISSUE TITLE
OR Data base storing procedure problem

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#116]
**RENEW/INACTIVE/STATUS 0**
This type of Status in the OPT must have ORDATE and ORNUM

**RENEWED/ACTIVE/STATUS R**
This type of Status should NOT have ORDATE and ORNUM

Please provide fixer to all the deployed branches to mitigate this problem.
System is currently NOT verifying any DUPLICATE ORNUMBER.
Please evaluate if OR Number should be technically UNIQUE.

**Comment by marzxxx90** [comment]
Fixer Updated, include also Penalty, Days Over Due, Renew Due and Redeem Due
branch: 13
