### ISSUE TITLE
PTU File Concern

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#119]
Sales PTU Files CustomerCoder must be UNIQUE or different per BRANCH

**Comment by marzxxx90** [comment]
Added text field for customer code in form settings
branch: 1.4 POS Customer Code

**Comment by cadeath** [comment]
Refer to https://github.com/cadeath/Dalton/issues/130

**Comment by marzxxx90** [comment]
Remove Code Lock

**Comment by cadeath** [comment]
Included in 1.4 - POS Main Branch

**Comment by cadeath** [comment]
Bug found
PTU file included its Stock In/Out items...

**Comment by cadeath** [comment]
Fixed
Included to 1.4 POS
