### ISSUE TITLE
Pawning

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#12]
Include POSITION in adding username, add APPRAISER as position
display only APPRAISER position in PAWNING module when NEW LOAN

**Comment by marzxxx90** [comment]
appraiser combo box fix.,only appraiser privilege will display in cboAppraiser

**Comment by cadeath** [comment]
What branch please

**Comment by marzxxx90** [comment]
In new loans.,only appraiser privilege will display in cboAppraiser.text combobox

**Comment by cadeath** [comment]
New Loans branch?

**Comment by marzxxx90** [comment]
Appraiser branch sir

**Comment by marzxxx90** [comment]
For Checking

**Comment by cadeath** [comment]
Unsai last commit ninyo?

**Comment by marzxxx90** [comment]
Update User Management sir

**Comment by marzxxx90** [comment]
sa User management ni na brach d i sir

**Comment by marzxxx90** [comment]
sa User Management na brach d i ni sir...last update, Update User Management

**Comment by cadeath** [comment]
Update from v1.2.2

**Comment by cadeath** [comment]
Please update from Version 1.2.2

**Comment by cadeath** [comment]
Cannot change PRIVILEGE
Please include Appraiser as DEFAULT

**Comment by cadeath** [comment]
Included in Issue #41

**Comment by cadeath** [comment]
Please write the detail before putting tags...
Read #47

**Comment by cadeath** [comment]
any update?

**Comment by marzxxx90** [comment]
fix na ni sir
refer issue #11

**Comment by cadeath** [comment]
Referred to issue #11 
Closed
