### ISSUE TITLE
Stock Transfer

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#120]
**Issue on stock transfer OUT**
Location should be dropdown list with BRANCH including PTU (PTU warehouse) and 01 (Warehouse)
STO# in the filename should be <branchCode><number:00000>

**Procedure**
1. Click Stock Out Mode
2. Punch the items you wanted to Stock Out
3. Click Post
4. Input STO#
5. Select Location
6. Encode Particulars, if any

PS: Please confirm if this has privilege

**Comment by Bladier** [comment]
Change textbox to dropdownlist, add branch(PTU warehouse and Warehouse)
branchname: Stock Transfer #120
Updated in 1.4 POS

**Comment by cadeath** [comment]
@marzxxx90 @cloudNine09  jayr
please verify

**Comment by cadeath** [comment]
Please post the system procedure also.
So that I will insert it to the Main Post

**Comment by cadeath** [comment]
Revise from 
PTU warehouse to PTU
and Warehouse to 01

**Comment by cadeath** [comment]
Please update to 1.4 - POS
Bug occur
Fix the Incrementation of the Control Number
Fix the Filename of the STO, it should be the control number

@Bladier @marzxxx90

**Comment by cadeath** [comment]
TESTING LIST
WRONG PIN, OK
CANCEL OTP, OK

Fixed the Incrementation of the Control Number
Fixed the Filename of the STO, it should be the control number

Included in 1.4 POS
