### ISSUE TITLE
POS Privilege

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#121]
Include new privileges

POS
StockOut
Returns

**Comment by marzxxx90** [comment]
Privileges  Added in User Management
Branch: 1.4-POS Privilege

**Comment by cadeath** [comment]
@Bladier  @cloudNine09  jayr
Please test and confirm so that it will be close.

Please verify if this request OTP, for record purposes only

**Comment by cadeath** [comment]
Remove POS privilege. Cannot Use Module. OK
Remove StockOut. Not working

Please check

@marzxxx90 JayR c/o @cloudNine09

**Comment by marzxxx90** [comment]
Unsa ning Remove StockOut sir?

**Comment by marzxxx90** [comment]
Can't shift Stock out mode if don't have Privilege
Branch: 1.4 POS Privilege
Updated from 1.4 POS

**Comment by cadeath** [comment]
@Bladier @cloudNine09  Please verify

**Comment by Bladier** [comment]
Okey, Can't shift stoct out if user don't have Privilege

**Comment by cadeath** [comment]
Noted
