### ISSUE TITLE
Cash Count Sheet

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#122]
Information on Cash Count sheet should be change
For Sales Return - Sales Return, not Sales
For Auction Redeem - Auction Redeem, not Auction

**Comment by cadeath** [comment]
Please verify if naga Reflect ang mga details.

**Comment by marzxxx90** [comment]
Updated Cash Count Name of Journal in POS
Brach: 1.4-POS CashCount
Updated From 1.4-POS
