### ISSUE TITLE
Insurance Transaction

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#124]
_**Enhancement**_  added on 1/16/17
- If IND 00001 is not existing, generate automatically. Same with RECALL 00
- After encode COI, ask the user if to encode another COI, yes and no. Making their work more easy

_**Current**_
Encode in Insurance Module and encode in POS Module

_**For development**_
Encode in Insurance Module only, generate POS Entries automatically

**Comment by cadeath** [comment]
Palihug tarunga inyung trabaho. 
Ang JE nagProduce og CASH COUNT ENTRY nagkaProb hinuon ang SYSTEM

**Comment by marzxxx90** [comment]
Added function for Deducting Inventory in every Transact of Insurance and Deduct if Void

**Comment by cadeath** [comment]
Checked

**Comment by cadeath** [comment]
Enhancement
 - If IND 00001 is not existing, generate automatically. Same with RECALL 00
 - After encode COI, ask the user if to encode another COI, yes and no. Making their work more easy

**Comment by marzxxx90** [comment]
included in version 1.5
