### ISSUE TITLE
LayAway Encoding

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#126]
**UPDATE 4/3/2017**
Added Lay Away Module
Function that Collect Minimum 20 % of Item Price upon first applying
Function for Auto Forfeit Item if Item Not Fully Paid after Forfeit Date
Function for Void Lay Away Plan and Payments
Add Journal
For Every Lay Away Payments
For Forfeit Lay Away Plan
Fix Journal Voiding Error in Payments

**Current on POS version**
Encode the Selling Price on the POS and Cash In the amount received. Inform the Accounting Department

**Enhancement Version**
Add a LayAway Module that will record each payment of a client

**Comment by marzxxx90** [comment]
Added
Lay Away Module 
Function that Collect Minimum 20 % of Item Price upon first applying
Function for Auto Forfeit Item if Item Not Fully Paid after Forfeit Date
Function for Void Lay Away Plan and Payments
Branch: Lay away
Updated from 1.4 POS

**Comment by marzxxx90** [comment]
Added Function for Uploading Exist Lay Away Plan

**Comment by marzxxx90** [comment]
Add Journal 
For Every Lay Away Payments
For Forfeit Lay Away Plan

**Comment by marzxxx90** [comment]
Fix Journal Voiding Error in Payments

**Comment by marzxxx90** [comment]
Included in version 1.5

**Comment by cadeath** [comment]
Please user manual on this one...
c/o Jayr
