### ISSUE TITLE
POS VOID

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#128]
Must have VOID

**Comment by cadeath** [comment]
Please post any update.
All Critical are urgent

**Comment by marzxxx90** [comment]
Added Void Function
Branch: 1.4-POS Void
Update from 1.4-POS

**Comment by cadeath** [comment]
@cloudNine09 urgent for checking c/o JayR

**Comment by cadeath** [comment]
NOT WORKING

please remove confirmation after OTP CODE
double check at ONHAND (PLU), INVENTORY, and DATABASE if it was updated and returned

**Comment by marzxxx90** [comment]
inventory add after item voided
branch: 1.4 POS Void
Updated from 1.4 POS

**Comment by cadeath** [comment]
Recall ITEM is not yet returned to inventory

**Comment by marzxxx90** [comment]
Recall Item Fix
Branch: 1.4 POS Void
Updated from 1.4 POS

**Comment by cadeath** [comment]
Checking the following
Transact single item
Transact multiple items
Transact single recall
Transact multiple recall

**Comment by cadeath** [comment]
Sales List form, disable auto resize

**Comment by cadeath** [comment]
*Bug*
Sales List AutoResize, Disable
Stock Card Void Item Display
Void Recall has "W" status, it should be "S"

**Comment by cadeath** [comment]
Checking the following
Transact single item
Transact multiple items
Transact single recall
Transact multiple recall

**Comment by marzxxx90** [comment]
**_Fix_** 
Auto Resize of Sales List Disable
Stock Card Displaying Void

**Comment by cadeath** [comment]
Checked
Included in 1.4 POS
