### ISSUE TITLE
JOURNAL ENTRIES SUMMARIZE ALL THE ACCOUNTS

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#13]
Journal Entries should be summarize when generated

**Comment by marzxxx90** [comment]
Journal Summary still on process
searching code in how to total the value of debit and credit

**Comment by cadeath** [comment]
Advice to add column on tblJournal, TransType.
Record New Loans, Renew, Redeem, Dollar, etc all sales transaction related

then you can SUMMARIZE it

**Comment by marzxxx90** [comment]
adding data on TRANSTYPE is ok
waiting for all sales transactions clarification
searching for multiple query execution

**Comment by cadeath** [comment]
Craft a Version 2 of function **ExtractJournalEntry** at **frmExtractor** form
I bet JOURNAL_ENTRIES view didn't fit in the problem

Algorithm will be
1. Get the DISTINCT TRANSTYPE for specific date.
2. Summary every TRANSTYPE depending on its COLUMN (Debit or Credit)
3. Save Summarized data in excel

**Comment by marzxxx90** [comment]
sql query for journal summarizing is ok
trying to apply in vb.net

**Comment by cadeath** [comment]
upload and post your sample transactions here.

please give me the summary of summarized transactions

**Comment by marzxxx90** [comment]
error in TRANSDATE can't be filter date




![output](https://cloud.githubusercontent.com/assets/19383754/15497030/28859fa6-21cb-11e6-8680-b1b873c98c68.png)

**Comment by marzxxx90** [comment]
![untitled](https://cloud.githubusercontent.com/assets/19383754/15497125/a456993c-21cb-11e6-8d7d-b0f672333095.png)

**Comment by cadeath** [comment]
Date is error because you don't have TRANSDATE on your VIEW

**Comment by marzxxx90** [comment]
TRANSDATE fix summary journal ok

**Comment by cadeath** [comment]
Sample data please

**Comment by marzxxx90** [comment]
[rpt_CashCountSheet.pdf](https://github.com/cadeath/Dalton/files/281068/rpt_CashCountSheet.pdf)

**Comment by marzxxx90** [comment]
![untitled](https://cloud.githubusercontent.com/assets/19383754/15529649/6646205c-2281-11e6-94d1-e826b9ac4edb.png)

**Comment by marzxxx90** [comment]
cannot send excel file, PDF or Picture file only

**Comment by cadeath** [comment]
Please remove the CUSTOM COLUMN in the excel file because it will affect the UPLOADING in the MAIN SERVER

**Comment by cadeath** [comment]
Please do it again
include OTHER SERVICES and their daily report

**Comment by marzxxx90** [comment]
[JRNL20160525ROX.xlsx](https://github.com/cadeath/Dalton/files/283616/JRNL20160525ROX.xlsx)
[JRNLNEWLOAN20160525ROX.xlsx](https://github.com/cadeath/Dalton/files/283619/JRNLNEWLOAN20160525ROX.xlsx)
[JRNLPADALAIN20160525ROX.xlsx](https://github.com/cadeath/Dalton/files/283620/JRNLPADALAIN20160525ROX.xlsx)
[JRNLPADALAOUT20160525ROX.xlsx](https://github.com/cadeath/Dalton/files/283621/JRNLPADALAOUT20160525ROX.xlsx)
[JRNLPADALAPMFTCIN20160525ROX.xlsx](https://github.com/cadeath/Dalton/files/283623/JRNLPADALAPMFTCIN20160525ROX.xlsx)
[JRNLPADALAPMFTCOUT20160525ROX.xlsx](https://github.com/cadeath/Dalton/files/283622/JRNLPADALAPMFTCOUT20160525ROX.xlsx)
[JRNLPERALINKIN20160525ROX.xlsx](https://github.com/cadeath/Dalton/files/283624/JRNLPERALINKIN20160525ROX.xlsx)
[JRNLPERALINKOUT20160525ROX.xlsx](https://github.com/cadeath/Dalton/files/283625/JRNLPERALINKOUT20160525ROX.xlsx)
[JRNLREDEMP20160525ROX.xlsx](https://github.com/cadeath/Dalton/files/283626/JRNLREDEMP20160525ROX.xlsx)
[JRNLRENEW20160525ROX.xlsx](https://github.com/cadeath/Dalton/files/283627/JRNLRENEW20160525ROX.xlsx)
[JRNLWESTERNIN20160525ROX.xlsx](https://github.com/cadeath/Dalton/files/283628/JRNLWESTERNIN20160525ROX.xlsx)
[JRNLWESTERNOUT20160525ROX.xlsx](https://github.com/cadeath/Dalton/files/283629/JRNLWESTERNOUT20160525ROX.xlsx)
[JRNL20160525ROX.xlsx](https://github.com/cadeath/Dalton/files/283630/JRNL20160525ROX.xlsx)
[JRNLBORROW20160525ROX.xlsx](https://github.com/cadeath/Dalton/files/283631/JRNLBORROW20160525ROX.xlsx)
[JRNLDOLLAR20160525ROX.xlsx](https://github.com/cadeath/Dalton/files/283632/JRNLDOLLAR20160525ROX.xlsx)
[JRNLGPRSIN20160525ROX.xlsx](https://github.com/cadeath/Dalton/files/283633/JRNLGPRSIN20160525ROX.xlsx)
[JRNLGPRSOUT20160525ROX.xlsx](https://github.com/cadeath/Dalton/files/283634/JRNLGPRSOUT20160525ROX.xlsx)
[JRNLINSUR20160525ROX.xlsx](https://github.com/cadeath/Dalton/files/283635/JRNLINSUR20160525ROX.xlsx)

**Comment by marzxxx90** [comment]
[rpt_Insurance.pdf](https://github.com/cadeath/Dalton/files/283664/rpt_Insurance.pdf)
[rpt_moneyTransfer.pdf](https://github.com/cadeath/Dalton/files/283665/rpt_moneyTransfer.pdf)
[rpt_RegisterNewLoan.pdf](https://github.com/cadeath/Dalton/files/283666/rpt_RegisterNewLoan.pdf)
[rpt_RegisterRedeem.pdf](https://github.com/cadeath/Dalton/files/283667/rpt_RegisterRedeem.pdf)
[JRNL20160525ROX.xlsx](https://github.com/cadeath/Dalton/files/283668/JRNL20160525ROX.xlsx)
[rpt_Dollar.pdf](https://github.com/cadeath/Dalton/files/283669/rpt_Dollar.pdf)

**Comment by marzxxx90** [comment]
[rpt_RegisterRedeem.pdf](https://github.com/cadeath/Dalton/files/283743/rpt_RegisterRedeem.pdf)
[rpt_RegisterNewLoan.pdf](https://github.com/cadeath/Dalton/files/283744/rpt_RegisterNewLoan.pdf)

**Comment by marzxxx90** [comment]
[JRNL20160527ROX.xlsx](https://github.com/cadeath/Dalton/files/283746/JRNL20160527ROX.xlsx)

**Comment by cadeath** [comment]
Unsaon nako ni pagCheck kung ISA lang ka TRANSACTION?

New loan, isa.

unsaon nako pagCheck sa SUM kung isa lang imong giTransact.


Ani nlng. pagTransact of 10 ka NEWLOAN
tpos pagProduce og JE.


if nagSUMMARIZE then try npud kag 10 ka NEWLOAN og 5 ka REDEEM

kung nagSUMMARIZE ang NEW LOAN OG REDEEM

**Comment by marzxxx90** [comment]
new loans

![1](https://cloud.githubusercontent.com/assets/19383754/15638369/4188f49a-2652-11e6-9f6f-1482b64a498a.png)
[JRNL20160525ROX.xlsx](https://github.com/cadeath/Dalton/files/288716/JRNL20160525ROX.xlsx)

**Comment by marzxxx90** [comment]
Renewals and Insurance

![2](https://cloud.githubusercontent.com/assets/19383754/15638373/4d579344-2652-11e6-9cb8-e188dc41b9d9.png)
![3](https://cloud.githubusercontent.com/assets/19383754/15638374/4d57fbae-2652-11e6-8353-7061f4e3de20.png)
[JRNL20160528ROX.xlsx](https://github.com/cadeath/Dalton/files/288717/JRNL20160528ROX.xlsx)

**Comment by marzxxx90** [comment]
database DDL
[add to database.txt](https://github.com/cadeath/Dalton/files/288718/add.to.database.txt)

**Comment by cadeath** [comment]
Human na ni?
Palihog commit tpos iUpdate ko

**Comment by marzxxx90** [comment]
ok na 2ng journal summary sir makita na ang wlay transtype ug naa kong may transtype ehh sum na niya ang debit ug credit kong wla ehh summary lng niya

**Comment by cadeath** [comment]
Noted. For Merging

**Comment by cadeath** [comment]
Patch included
For testing

**Comment by cadeath** [comment]
Already merge and ready for checking
For Review

**Comment by cadeath** [comment]
@marzxxx90 please post the details ACCOUNTING'S CONCERNS
@cloudNine09

**Comment by marzxxx90** [comment]
ok na ni sir...na pakita na nko sa iyaha ang sample sa report ok daw

**Comment by cadeath** [comment]
unsang sample report? :P db excel file mani

**Comment by marzxxx90** [comment]
ou sir 2ng excel file..2ng journal entries na report...gi demo nko sa iyaha kong unsa ang output sa report

**Comment by marzxxx90** [comment]
NOTE: Mali ang summary position(wala nagpartner ang RF)

**Comment by cadeath** [comment]
TRANSID on JOURNAL don't have VALUES, it only as NULL

Multiple BUG occurred in ROXAS database.
Please provide the database @cloudNine09 

THIS IS URGENT

**Comment by marzxxx90** [comment]
ok na ni sir sa Void erro 2ng may problem

**Comment by cadeath** [comment]
Please confirm if this was include in 1.2.2.8

**Comment by marzxxx90** [comment]
naa nani sa 1229 sir..sabay ni sa OTP

**Comment by cadeath** [comment]
Included in V1.2.2.9
