### ISSUE TITLE
Selling Price change from 2 to 6 decimal places

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#132]
As per incident, the P4.95 should be P5  or almost closer to P5
As per advice by Sir Dennis, change the decimal into 6.

Output should reflect in the PTU file (Sales) having 6 decimal places.

**Comment by marzxxx90** [comment]
Created Decimal Fixer for table Doclines 
Branch: 1.4-POS Decimal Fixer
Updated from 1.4-POS

**Comment by cadeath** [comment]
Please provide Fixer

**Comment by cadeath** [comment]
@marzxxx90  Jayr c/o @cloudNine09 
For discussion

Any comment on changing 6 decimal places including

QTY, SALEPRICE, UNITPRICE, and ROWTOTAL

**Comment by cadeath** [comment]
Please fix, cannot drop the table DOCLINES on the existing database. any Idea?

**Comment by cadeath** [comment]
1. Check the database structure, change 6 decimal places on QTY, SALEPRICE, UNITPRICE, and ROWTOTAL for DOCLINES and INVLINES
2. Provide Fixer for DOCLINES and INVLINES
3. Provide Patcher for this new structure
4. Set the database into 1.2.3.2

**Comment by marzxxx90** [comment]
Invlines Included to fixer
branch:1.4 Decimal Fixer
Updated from 1.4 POS

**Comment by cadeath** [comment]
Please verify this check list

1. Check the database structure, change 6 decimal places on QTY, SALEPRICE, UNITPRICE, and ROWTOTAL for DOCLINES and INVLINES
2. Provide Fixer for DOCLINES and INVLINES
3. Provide Patcher for this new structure
4. Set the database into 1.2.3.2

**Comment by cadeath** [comment]
Please provide update on the checklist above.

also
PTU file decimal places worked. changed in 6 decimal places

**Comment by cadeath** [comment]
1. Check the database structure, change 6 decimal places on QTY, SALEPRICE, UNITPRICE, and ROWTOTAL for DOCLINES and INVLINES [OK]
2. Provide Fixer for DOCLINES and INVLINES [OK]
3. Provide Patcher for this new structure [OK]
4. Set the database into 1.2.3.2 [OK]
