### ISSUE TITLE
URGENT deployment for Version 1.4.1.10

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#133]
Here are the list of URGENT that needs for the next working patch.

https://github.com/cadeath/Dalton/issues/132 Selling Price to 6 dec places [OK]
https://github.com/cadeath/Dalton/issues/128 VOID Module for POS [OK]
https://github.com/cadeath/Dalton/issues/121 POS Privilege [OK]
https://github.com/cadeath/Dalton/issues/120 Stock Transfer [OK]
https://github.com/cadeath/Dalton/issues/119 PTU File Concern [OK]
https://github.com/cadeath/Dalton/issues/38 Apprased by No display [OK]
https://github.com/cadeath/Dalton/issues/141 Re-transact with 0 selling price wrong computation [OK]

Please provide TEST SHEETS before deployment

* for checking

**Comment by marzxxx90** [comment]
All Urgent For Checking

**Comment by cadeath** [comment]
Please update in their threads.
I will include later another URGENT.
after all urgent were completed, prepare a testing sheet for testing purposes

**Comment by cadeath** [comment]
https://github.com/cadeath/Dalton/issues/38 Already included

**Comment by cadeath** [comment]
https://github.com/cadeath/Dalton/issues/136 is Included, OTP Required

**Comment by cadeath** [comment]
Please check then provide installer

**Comment by cadeath** [comment]
https://github.com/cadeath/Dalton/issues/141 is included. Re-Transact 0 selling price

**Comment by cadeath** [comment]
https://github.com/cadeath/Dalton/issues/119 Bug found by the accounting

**Comment by cadeath** [comment]
@marzxxx90  please update me on Appraiser

**Comment by cadeath** [comment]
https://github.com/cadeath/Dalton/issues/136 is included in https://github.com/cadeath/Dalton/issues/120

**Comment by cadeath** [comment]
Prepare Test Sheet and Installation

Prepare Fixer and Update GAI
If everything is deployed. I will close this thread

**Comment by cadeath** [comment]
Done, last 12/28/16
