### ISSUE TITLE
Sales PTU File Extraction move to Tools

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#135]
PTU Sales file extraction should satisfy the following conditions

1. Can be executed after close the store
2. File name will be base on the EXTRACTED DATE

**Comment by marzxxx90** [comment]
Transfer PTU file Extractor into Tools
PTU cannot be extracted if system open same as current date
Branch: 1.4 POS PTU Extract
Updated from 1.4-POS

**Comment by cadeath** [comment]
CHECKING...

BUG
Disable Sales Extractor when no user is login * FIXED
Disable Void Report when no user is login * FIXED

**Comment by cadeath** [comment]
Generate when Closed. OK
Generate previous date when OPEN. OK
Can't generate current when OPEN. OK
Generate Filename with the SelectedDate. OK

To be included in the Main Branch 1.4-POS
