### ISSUE TITLE
Stock Out Mode requires OTP

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#136]
Include another OTP for Stock Out Mode
Remove it from Privileges

**Comment by marzxxx90** [comment]
Added OTP in Stock Out Mode
branch:1.4 OTP for Stock Out
Updated From 1.4 POS

**Comment by cadeath** [comment]
HOLD until few days before deployment
But will be checked ASAP

**Comment by cadeath** [comment]
Included in 1.4 POS
