### ISSUE TITLE
One-Time Password (OTP) Management 

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#137]
This new Module is use to Enable/Disable OTP request per module
Design a comprehensive that will easily add/edit/remove OTP request

May include also cases like choose OTP or Privilege

**Comment by cadeath** [comment]
Please provide

We need an interface

**Comment by marzxxx90** [comment]
unsa na transaction ang butangan ug option na OTP or Privilege sir

**Comment by marzxxx90** [comment]
Added OTP Interface & OTP Control
