### ISSUE TITLE
Menu function change location

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#138]
Include in the TOOLS menu the following
IMD Import - Importing Item Master Data
STO Import - Importing Stock Transfer Files
PTU Sales - Extract Sales (PTU File) for SAP A/R

Include in the REPORTS menu the following
Sales Report
Inventory Report

**Comment by marzxxx90** [comment]
IMD, STO AND PTU added in tools menu
Sale Report and Inventory Report added in Report Menu
Branch: Menu Location Change
Updated from 1.4 POS

**Comment by cadeath** [comment]
Please double check if what are their status when user is not login yet

**Comment by marzxxx90** [comment]
No User Yet ang status sir kong wla naka login
