### ISSUE TITLE
POS Delete Key

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#140]
If any wrong punch occurs
Pressing delete after selecting the item you want to remove will be efficient

Provide a function that remove both
in LISTVIEWITEM
HashTable of the Purchase Items

for easy removing of items and clean code function

**Comment by Bladier** [comment]
Enhancement add some validation if no selected item in LISTVIEWITEM then 
item will be the same.  Popup message to confirm if selected item really want to remove.
Updated: From 1.4 POS version
branch name : POS Delete Key #140

**Comment by cadeath** [comment]
Please revise, update on 1.4 POS

The problem here is cleaning the codes well. Deleting product using DELETE key sometimes won't update the HASHTABLE which was used in saving information. It should be sync with ListItem

**Comment by cadeath** [comment]
add Item and delete then post, result NOTHING TO BE SAVE
post two item, delete one then post, result POSTED and only the posted item is extracted in the PTU file

Cleared
