### ISSUE TITLE
Loan Register Report

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#15]
Renewed Pawnticket displays 00000

**Comment by cadeath** [comment]
Please trace this problem

**Comment by Blade1992** [comment]
Loan Register Report Recheck, No found PT 00000
I try to transact New Loan and Renew then Display Report, All PT number are Okey.

**Comment by cadeath** [comment]
please ask for database from the BRANCH

@cloudNine09  please assist

**Comment by cadeath** [comment]
any update?

**Comment by Blade1992** [comment]
No PT 00000 found.
