### ISSUE TITLE
Print Layout

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#152]
Check the CURRENT LAYOUT

Effective Interest Rate (TBD w/ Sir Dennis)

- [x] Get the computation for Effective Interest Rate

ID Presented field (TBD w/ Sir Dennis)
What if multiple ID

- [x] CP Number is required

**Comment by marzxxx90** [comment]
EIR =( (AdvInt + Service Charge) * Interest Rate) / Net Amount

**Comment by marzxxx90** [comment]
Added trap to required CP number
branch: Compliance
Updated from 1.4 POS

**Comment by marzxxx90** [comment]
Already Included in latest version
