### ISSUE TITLE
KYC Compliance for Client Management

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#153]
Review the AMLA about KYC
CP Number required
Customer Profiling: LOW, NORMAL, HIGH

**Comment by cloudNine09** [comment]
Here are the list of KYC requirements base on Ma'am Nora's list:
Name
Present Address
Permanent Address
Date and place of birth
Nationality
Nature of work with name of employer or nature of business
Contact number
TIN, SSS or GSIS no.
Specimen signature
Source of fund(s)
Name of beneficiaries in case of insurance contracts
Whenever applicable

**Comment by cadeath** [comment]
To finalize
We will include the information that was given by Maam Nora and include the Customer Profile with 3 tags, LOW, NORMAL, HIGH

**Comment by cloudNine09** [comment]
Here are the List of Valid Identification Card of AMLA
Passport
Driver’s License
Professional Regulation Commission (PRC) ID
National Bureau of Investigation (NBI) Clearance
Police Clearance
Postal ID
Voter’s ID
Barangay Certification
Government Service Insurance System (GSIS) e-Card
Social Security System (SSS) Card
Senior Citizen Card
Overseas Workers Welfare Administration (OWWA) ID
OFW ID
Seaman’s Book
Alien Certification of Registration/Immigrant Certificate of Registration
Government Office and GOCC ID, e.g. Armed forces of the Philippines (AFP ID), Home Development Mutual Fund (HDMF ID)
Certification from the National Council for the Welfare of Disabled Persons (NCWDP)
Department of Social Welfare and Development (DSWD) Certification
INTEGRATED BAR OF THE PHILIPPINES ID
COMPANY IDs ISSUED BY PRIVATE ENTITIES OR INSTITUTIONS REGISTERED WITH OR SUPERVISED OR REGULATED EITHER BY THE BSP,  SEC OR IC

**Comment by Bladier** [comment]
Meetingan nato ni sir.

**Comment by cadeath** [comment]
Nganu man?

**Comment by marzxxx90** [comment]
Already Deployed in Version 1.6.0
