### ISSUE TITLE
OTP Control Separation

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#155]
Feb 7, we discussed of OTP turn-over.
We will now separate OTP depending on its user.

OTP Manager
1. Add OTP - It has a Control Name to Identify its function
2. Assign Modules in specific OTP

Criteria
No different OTP on a single Module

NOTE:
NEGLIENCE c/o OPERATION(AO)
CHANGE PAD c/o OPERATION(AO)
PRIVILEGES c/o HR
PULLOUT c/o REMATADO
SYSTEM ERROR c/o MIS

**Comment by marzxxx90** [comment]
Reference #113 #137

**Comment by marzxxx90** [comment]
Separate OTP per Transaction
Branch: OTP by Module
Updated from 1.4 POS

**Comment by marzxxx90** [comment]
OTP Separated:
Voiding
User Management
Setting Module
Inventory
Pullout
Stock out

**Comment by cadeath** [comment]
Please provide an interface for easy management of OTP
https://github.com/cadeath/Dalton/issues/137

**Comment by marzxxx90** [comment]
Added OTP interface & OTP Control
