### ISSUE TITLE
Report - Fixing

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#157]
Outstanding Loan
 - No Segregated included

Segregated List
 - Filter on Auction List and Withdraw date
 - Include daily and monthly

**Comment by marzxxx90** [comment]
Removed Segre from Oustanding Report

**Comment by marzxxx90** [comment]
Ang Auction List maapil ang Redeem sir

**Comment by marzxxx90** [comment]
Ang Auction List maapil ang Redeem Sir

**Comment by marzxxx90** [comment]
Segregate List Updated
