### ISSUE TITLE
New Categories and Pawning System

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#158]
Approved on 2/10/2017

Category: Gadget 2+15
ItemClass: Cellphone, Tablet

Change Date Computation
Loan to Maturity = 29 days (first day is counted as 1)
Maturity to Expiry = 30 days
Expiry to Auction = 15 days

eg
L = 1/1/2017
M = 1/30/2017
E = 3/1/2017
A = 3/16/2017

**Comment by marzxxx90** [comment]
Pawning Date Computation Change
Branch: New Category
Updated from 13
