### ISSUE TITLE
Adjustment for Inventory

### ISSUE THREAD

**Issue by Bladier** [cadeath/Dalton#162]
Add adjustment Module in Audit Console.

**Comment by marzxxx90** [comment]
Branch: Import STO

**Comment by marzxxx90** [comment]
added adjustment module, patcher for new table Item History (Records of adjusted Item) and Fixer for Item History
Branch: Import STO
Updated from 1.4 POS

**Comment by marzxxx90** [comment]
Included in version 1.5

**Comment by cadeath** [comment]
Wala lage ni sa ChangeLog
Please verify

**Comment by marzxxx90** [comment]
sa 1.4 mani na version updated

**Comment by cadeath** [comment]
For testing
Get Branch DB with Inventory

**Comment by cadeath** [comment]
NOT FUNCTIONING

Please double check the Zero Out and not Zero Out

**Comment by marzxxx90** [comment]
Fix Inventory Zero Out 
Branch: 1.5

**Comment by cadeath** [comment]
Checked
working on Branch 1.5
