### ISSUE TITLE
Layaway Report

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#163]
Current Lay-Away Items
-Item Code
-Description
-Client Name
-LayAway Date
-Forfeited Date
-Balance
-Payment

**Comment by marzxxx90** [comment]
Added New report Layaway List
branch: layaway
Updated from 1.4 POS

**Comment by cadeath** [comment]
LAYAWAY PAYMENTS REPORT - ok -DAILY
LAYAWAY LIST - sort the doc Date in Ascending. Remove the WhiteLines -DAILY
FORFEIT REPORT - Remove the WhiteLines. Make it more presentable - DAILY

INCLUDE MONTHLY
-PAYMENTS REPORTS
-LAYAWAY LIST
-FORFEIT REPORT

Add Summary in the Bottom

**Comment by marzxxx90** [comment]
Unsa na summary sir
wala may Monthly ang Layaway List same man ni sa Outstanding Loan
