### ISSUE TITLE
Version 1.5 Check List

### ISSUE THREAD

**Issue by marzxxx90** [cadeath/Dalton#166]
- [x] Layaway
- [x] Coi
- [x] Otp Separeted
- [x] New Setting Gui and Maintenance Options (Control Number & Branch Address)
- [x] SMS Module for Expiry
- [x] Inventory Adjustment
- [x] OTP Monitoring
- [x] Delete Key
- [x] Layaway Report
- [x] No Segre in Oustanding
- [x] Fix Segre List

**Comment by cadeath** [comment]
PakiElaburate ang COI kung unsa ni.

pakiEnumerate kung unsang SEPARATION imong gibuhat.

For record purposes.

**Comment by cadeath** [comment]
Please update this, include the following:
https://github.com/cadeath/Dalton/issues/163
https://github.com/cadeath/Dalton/issues/162
https://github.com/cadeath/Dalton/issues/157
https://github.com/cadeath/Dalton/issues/157
https://github.com/cadeath/Dalton/issues/140
https://github.com/cadeath/Dalton/issues/126
https://github.com/cadeath/Dalton/issues/102

Please include in the checking and be included in Changelog

**Comment by cadeath** [comment]
https://github.com/cadeath/Dalton/issues/124 Please check if this is also included.

**Comment by marzxxx90** [comment]
naa nani tanan sa version 1.5 sir

**Comment by cadeath** [comment]
Please provide a complete list because on the list above including the other threads...
For documentation purposes only
