### ISSUE TITLE
SMS Module

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#167]
Expiry Notification Form

- [x]  Include Expiry Date and Auction Date in the display
- [x] Include view Pawnticket Information
- [x] Enhance SMS Notification Report, include header, change date into DATE without time

Report
 - Daily Summary of Notice
 - Monthly Summary of Notice

**Comment by cadeath** [comment]
Include Expiry Date and Auction Date in the display
Include view Pawnticket Information

Done

**Comment by marzxxx90** [comment]
Added Daily & Monthly Expiry List
SMS Notification Added Header & Footer
Branch: 1.5

**Comment by cadeath** [comment]
Revised in SMS branch
Please pull to 1.5 and close

**Comment by marzxxx90** [comment]
Merging Done

**Comment by cadeath** [comment]
Bug found
Branch with no internet has recorded a SENT status to the database

**Comment by cadeath** [comment]
CHECKED
Already implemented
