### ISSUE TITLE
Auto Deploy

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#171]
Program that automatically UPDATE/INSTALL all DIS over the branches
It has a Repository for Config File and for the programs (patches and installer)

This only requires WEBSERVER (apache) that has a disconfig.xml in the root directory.
disconfig.xml contains instruction on what to do with the current system installed, either to reinstall or to patch up.

disconfig.xml and programs can be place in different online repository but insure that disconfig.xml will be located by the Auto Deploy software and the programs are listed in the disconfig.xml

**Comment by marzxxx90** [comment]
Allow to display notification if there are updates
Automatic force close if system running
