### ISSUE TITLE
SMART MONEY ENDING BALANCE REPORT

### ISSUE THREAD

**Issue by cloudo9** [cadeath/Dalton#176]
ABLE TO VIEW AND GENERATE REPORT OF SMART MONEY ENDING BALANCE.

**Comment by marzxxx90** [comment]
Allow to display Smart Money Padala, Load Wallet & Eload (Retail Load) in Daily Cash Count

**Comment by marzxxx90** [comment]
Branch Cash Count with Smart Product
Updated from 1.6

**Comment by marzxxx90** [comment]
Included in version 1.6
