### ISSUE TITLE
BDO ATM CASHOUT

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#20]
BDO ATM Cashout didn't reflect on the reports

**Comment by marzxxx90** [comment]
added "null" l to sql query where Type not equal
to load all categories

**Comment by cadeath** [comment]
Human na ni?
unsai branch

**Comment by marzxxx90** [comment]
BDO ATM CASHOUT sir

**Comment by cadeath** [comment]
Please confirm kung na MERGE na ni sa 122 na branch

**Comment by marzxxx90** [comment]
Already merge to v122 sir

**Comment by cadeath** [comment]
please follow #47 for proper documentation

**Comment by cadeath** [comment]
palihog check sa v122 kung ok na :+1:

**Comment by cadeath** [comment]
@marzxxx90 please respond

**Comment by marzxxx90** [comment]
ok na ni sir..naa nani sa 1229
