### ISSUE TITLE
Money Exchange

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#27]
Allow the System to accept any kind of Currency

**Comment by Blade1992** [comment]
Currency table structure was done. 
The GUI was done.
Coding is on process.

**Comment by cadeath** [comment]
Follow this step
1. Input: Currency, Denomination, Rate
2. Save Transaction
3. Save Journal Entry (addJournal function)

Add Report per Currency
Test if the Journal Entry is Correct

**Comment by Blade1992** [comment]
Sir error occur when I load the currency from the database to listview.
the error was these. System.data.odbc.odbcexception(0x8013937):Error[hy000][odbc Firebird Driver][Firebird]Dynamic Sql Error
SQL error = - 104

**Comment by Blade1992** [comment]
Sr
Inpurt: Currency, Denomination, Rate is okey.
Save transaction is okey. 
Save to Journal Entry is okey.
The Report is on going.

**Comment by cadeath** [comment]
Make a DAILY and MONTHLY REPORTS

Craft a report and propose it here.
Please inform JayR to check this Module for Foreign Exchange and tell him to post a reply here

**Comment by Blade1992** [comment]
Sir hindi pa natapos ang report.

**Comment by cadeath** [comment]
unsai wala pa? XD
kabalo ka magHimog report?

**Comment by Blade1992** [comment]
Naglibog ko sa report sir..

**Comment by cadeath** [comment]
lahi ang libog sa tagalog, pagSure
unsai prob? himo og imong report sample icheck nato

**Comment by Blade1992** [comment]
hahhahah.. okey Sir Try nako buhat.

**Comment by Blade1992** [comment]
SIR patulong sa report bukas kunti nalang  kulang para magenerate nya ang monthly ug daily report

**Comment by cadeath** [comment]
tagai kog VIEW sa imong report

**Comment by Blade1992** [comment]
![dollarmonthdailyreport](https://cloud.githubusercontent.com/assets/19383719/15559793/e553a838-2317-11e6-954a-cf0cef0d3ad9.png)
Sir ito yung Design ng report ninagdagan ko nang Parameter which is Currency.

**Comment by cadeath** [comment]
Any update?

**Comment by Blade1992** [comment]
Sample Monthly Report
![report](https://cloud.githubusercontent.com/assets/19383719/15624767/eae5515e-24c3-11e6-8d6b-d7054f02dd43.png)

**Comment by Blade1992** [comment]
Sir mao ning DDL sa currency nga Table sir.
[DDL list.txt](https://github.com/cadeath/Dalton/files/287576/DDL.list.txt)

**Comment by Blade1992** [comment]
Sir sample summary sa monthly
![dollar report monthly](https://cloud.githubusercontent.com/assets/19383719/15625481/72cabf6c-24da-11e6-8573-310814c8f636.png)
![dollar report monthly1](https://cloud.githubusercontent.com/assets/19383719/15625482/75b7cf62-24da-11e6-8b7f-a9795b3a6b4c.png)

**Comment by Blade1992** [comment]
Dollar Report Daily sample
![dollar report daily](https://cloud.githubusercontent.com/assets/19383719/15625485/86356e6c-24da-11e6-9912-78a6cf391de4.png)

**Comment by cadeath** [comment]
Please give me your DDL on the database so that I can include a AUTOPATCH on the system

**Comment by Blade1992** [comment]
[DDL list.txt](https://github.com/cadeath/Dalton/files/290648/DDL.list.txt)

**Comment by Blade1992** [comment]
Yan sir ang DDL.

**Comment by cadeath** [comment]
For merge

**Comment by cadeath** [comment]
**_PLEASE REVISE THE FUNCTIONALITY_**
**Viewing Currency**
Confuse, the usage of word "View" and "Select"

**Tab Index Priority**
1. Currency Field
2. Denomination
3. Rate
4. Calculate
5. _**Serial**_
6. _**Name**_
7. Save
8. Cancel
9. Browse

**Swap Fields**
Interchange Name and Serial

I cannot merge a buggy.

**Comment by Blade1992** [comment]
Already make changes in Money Exchange Form.

**Comment by cadeath** [comment]
Ready in Version 1.2.1

**Comment by Blade1992** [comment]
Unsa pa i Update ani sa Money Exchange Sir?

**Comment by cadeath** [comment]
For review na ni

**Comment by cadeath** [comment]
Included in version 1.2.2
