### ISSUE TITLE
New Report - Monthly Transaction Count Summary

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#28]
New report that display the count of ALL transactions (Sales related) on each they of the month

**Comment by cadeath** [comment]
Type should be:

1. Pera Padala
2. New Loans
3. Renewals
4. Dollar
5. BDO ATM
6. ECPAY
7. GPRS
8. Ticketing
9. PeraLink
10. Western Union
11. Retail
12. Insurance
13. Smart Money Padala
14. Load Wallet
15. Redemption

**Comment by marzxxx90** [comment]
added new report..Monthly Transaction Count Summary
Monthly Transaction Count Summary Branch

**Comment by cadeath** [comment]
before "FOR CHECKING" Label, please follow #47 

Please update it from Branch 122 also

**Comment by marzxxx90** [comment]
added new report..Monthly Transaction Count Summary
Monthly Transaction Count Summary Branch
already update from branch 122

**Comment by cadeath** [comment]
Please update from branch 1.2.2
Include this report on MONTHLY REPORT
Include it at the DROPDOWN list

**Comment by marzxxx90** [comment]
All done sir

**Comment by cadeath** [comment]
Please follow the instructions.

- [ ] Monthly Report should have dates daily (check the other monthly reports)

**Comment by cadeath** [comment]
Included in Version 1.2.2
