### ISSUE TITLE
Change Entries on Pawing

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#33]
As Per Sir Dennis, pawning Entries, Renewal and Redemption, should be changed
[DALTON CHANGE OF ACCOUNTV2.xlsx](https://github.com/cadeath/Dalton/files/269543/DALTON.CHANGE.OF.ACCOUNTV2.xlsx)

**Comment by Blade1992** [comment]
Regarding in money exchange when I load the currency there was error occur.
The printscreen is here.

**Comment by cadeath** [comment]
I think you are referring to the OTHER thread, not here ^_^

**Comment by cadeath** [comment]
It was already included in Version 1.2
For Monitoring
