### ISSUE TITLE
Change Rate

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#35]
Bug on Change Rate
when rate table's rows is greater than rate file's rows
excess rows will be REMAIN and the rest is modified.

instructions should be
1. Delete all rows
2. Populate the empty rate table by the rate file

**Comment by Blade1992** [comment]
Sir asa nimo ginakuha ang update ani Sir. kaning gina pakaon sa patcher nga mag update ug rate?

**Comment by cadeath** [comment]
db ingon ko sa ADMIN na program?

**Comment by Blade1992** [comment]
I mean sir katong Rate nga CIR file.

**Comment by Blade1992** [comment]
****

**Comment by Blade1992** [comment]
db.Log = Console.Out
' Specify order to be removed from database.
Dim reqOrder As Integer = 10252

' Fetch OrderDetails for requested order.
Dim ordDetailQuery = _
From odq In db.OrderDetails _
Where odq.OrderID = reqOrder _
Select odq

For Each selectedDetail As OrderDetail In ordDetailQuery
    Console.WriteLine(selectedDetail.Product.ProductID)
    db.OrderDetails.DeleteOnSubmit(selectedDetail)
Next

' Display progress.
Console.WriteLine("Detail section finished.")
Console.ReadLine()

' Determine from Detail collection whether parent exists.
If ordDetailQuery.Any Then
    Console.WriteLine("The parent is present in the Orders collection.")
    ' Fetch order.
    Try
        Dim ordFetch = _
        (From ofetch In db.Orders _
        Where ofetch.OrderID = reqOrder _
        Select ofetch).First()

        db.Orders.DeleteOnSubmit(ordFetch)
        Console.WriteLine("{0} OrderID is marked for deletion.,", ordFetch.OrderID)

    Catch ex As Exception
        Console.WriteLine(ex.Message)
        Console.ReadLine()
    End Try

Else
    Console.WriteLine("There was no parent in the Orders collection.")

End If


' Display progress.
Console.WriteLine("Order section finished.")
Console.ReadLine()

Try
    db.SubmitChanges()

Catch ex As Exception
    Console.WriteLine(ex.Message)
    Console.ReadLine()

End Try

' Display progress.
Console.WriteLine("Submit finished.")
Console.ReadLine()

**Comment by cadeath** [comment]
Any update?

**Comment by Blade1992** [comment]
Sir okey na ang Change Rate.

**Comment by Blade1992** [comment]
Ma delete na niya sir ang tanan nga Rows

**Comment by Blade1992** [comment]
![changerate](https://cloud.githubusercontent.com/assets/19383719/15731272/58e25a90-28a6-11e6-92dc-bbc9ed5a707a.png)

**Comment by Blade1992** [comment]
![changerate1](https://cloud.githubusercontent.com/assets/19383719/15731279/62c173ca-28a6-11e6-8879-a00e85db5f30.png)

**Comment by Blade1992** [comment]
For checking...

**Comment by cadeath** [comment]
For Merging

**Comment by cadeath** [comment]
was removed for Merging

Please do this instruction
Load 5 rows of data in a table
Load 3 rows of data in a table
Check the table if it was 3 rows

Please use branch Change-Rate

**Comment by cadeath** [comment]
Any update

**Comment by cadeath** [comment]
If magTag tag "For Checking" paki elaborate ang detail sa changes para maView og tarung.

**Comment by cadeath** [comment]
#47 please follow this

**Comment by Blade1992** [comment]
Delete all rows from database then update new data to database.
Changes: DoUpdate function.

**Comment by cadeath** [comment]
Na update na nimo ni sa 122?
palihog follow sa #47

**Comment by Blade1992** [comment]
Change Rate Update to 122 version.
Delete all rows from database then update new record set.

**Comment by cadeath** [comment]
Checking

**Comment by cadeath** [comment]
Included in earlier version of 1.2.2.8
