### ISSUE TITLE
BUG on beta for 1.2

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#37]
Compute base on Auction Date less Loan Date [DONE]
Client History report not correct

**Comment by cadeath** [comment]
Included in V1.2.0.1

**Comment by cloudNine09** [comment]
Dalton Kidapawan said, Incomplete.

**Comment by cadeath** [comment]
Please check their version.
Ask the system admin of their version and where can you find the version.

**Comment by cadeath** [comment]
https://github.com/cadeath/Dalton/issues/46

**Comment by cadeath** [comment]
Included in the early version of 1.2.2.8
