### ISSUE TITLE
No Display in Appraised by

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#38]
Didn't display Appraised by for NON-JEWELRY

Credit by: Regine Dijan

**Comment by cadeath** [comment]
Fixed
Included in Version 1.2

**Comment by cloudNine09** [comment]
Dalton Digos2: 
INCOMPLETE
NO DISPLAY IN APPRAISED BY IN NON-JEWELRY ITEM

**Comment by cloudNine09** [comment]
Dalton Kidapawan said, Incomplete.

**Comment by cadeath** [comment]
Please check their version.
Ask the system admin of their version and where can you find the version.

**Comment by cadeath** [comment]
https://github.com/cadeath/Dalton/issues/46

**Comment by cadeath** [comment]
@cloudNine09 jayr @marzxxx90 
Please double check if included

**Comment by marzxxx90** [comment]
asa ni na report makita sir?

**Comment by cadeath** [comment]
Current version 1.3 don't display APPRAISED BY <Appraiser Name>
Please be advice

**Comment by marzxxx90** [comment]
Naa naman ni sa 1.3 sir

**Comment by cadeath** [comment]
db automatic man na kuhaon ang Appraiser name tpos ibutang? wala man jud na data na nakaSave...
pahilog ko kay sa 1.4 wala xa. dapat naa sa Description sa ubos.

**Comment by marzxxx90** [comment]
Included na ni sa 1.4 POS sir

**Comment by cadeath** [comment]
Butangig APPRAISED BY sa ubos sa description

**Comment by marzxxx90** [comment]
Fix no display Appraiser in PT (New Loan & Renew)
Branch: No Display Appraiser
Updated from 1.4 POS

**Comment by cadeath** [comment]
Checked from 1.4 POS
