### ISSUE TITLE
Voiding Error

### ISSUE THREAD

**Issue by Arskie** [cadeath/Dalton#39]
all transaction pag mag void dapat dili na magamit ang pawn ticket na na void na para dili mag ka error or mag ka shortage sa reports.

**Comment by cadeath** [comment]
Check all VOID feature if they will disallow the usage of the VOID DocNum (PT#, OR, ME, MR, COI, etc)

**Comment by Blade1992** [comment]
If the transaction is void then then transaction number can not be used.
PT#,OR#,ME#,MR#,COI was check.

**Comment by cadeath** [comment]
Mau na imong himuan og way.
Saving has 3 tables affected.
1. Main table
2. Journal
3. Daily Time Log

PagmagVoid, dapat VOIDED ang tatlo

never pud FOR CHECKING kung dili pa human og wala pa nimo na commit sa main nato. v122

**Comment by Blade1992** [comment]
Void transaction in journal,Daily Time Log and all Table in the database transaction.
Transaction Number will not be use again if Transaction Number was already Used.
Void Checking Done.

**Comment by cadeath** [comment]
Please check @marzxxx90

**Comment by Blade1992** [comment]
Changes: Add TransID in journal table, add TransID in Daily Time Log table.
Update all transaction that has void.
The transacion Number will not used Again if it is already used.
Void Transaction in Journal and also Daily Time Log.
Already Updated in version 122.
Branch Name: Void Checking

**Comment by cadeath** [comment]
@marzxxx90  any update?

**Comment by marzxxx90** [comment]
OK na ni sir..na check na nko

**Comment by marzxxx90** [comment]
added column TRANSID for tbljournal and tbldailytimelog in patch
already updated to 122
branch void checking

**Comment by cadeath** [comment]
@marzxxx90 any update? naCheck na nimo ni?
@Arskie please verify
@cloudNine09 please note

**Comment by marzxxx90** [comment]
ou sir

**Comment by cadeath** [comment]
@Arskie please verify kung functioning para maINCLUDE nq sa 1.2.2

**Comment by cadeath** [comment]
@cloudNine09 pakiFollowup si @Arskie ani

**Comment by cadeath** [comment]
Included in V1.2.2.4

**Comment by Bladier** [comment]
Include TransID in OPen Store and Close Store.
Updated in V1.2.2.4 
Fixed.

**Comment by Bladier** [comment]
Fix Void transaction in the insurance.
Updated in V1.2.2.5
Fixed.
branchName: Void Checking

**Comment by Bladier** [comment]
FIX VOID TRANSACTION IN THE MONEY TRANSFER
UPDATED IN V1.2.2.5
FIXED.
branchName: Void Checking

**Comment by cadeath** [comment]
FOR CHECKING @marzxxx90  @Arskie

**Comment by marzxxx90** [comment]
Ok na ang mga void 2ng mga nag error.,na fix na ni ellie 2 tanan..na check na pud nko.,wala nay mag pop up na Journal Entries not found..geh specific ra niya ang transtype ato

**Comment by Arskie** [comment]
isahon nalang nko og check pag naka 1225 na taga e lang kog patch ani.

**Comment by cadeath** [comment]
As per meeting, as soon as na check napud nila ang branch 122, himuan na nakog installer ni para macheck nimo @Arskie 

@marzxxx90 @cloudNine09

**Comment by cadeath** [comment]
Please verify
unsa na Branch ni naInclude?

**Comment by Bladier** [comment]
Na update ni sa OTP nga branch sir

**Comment by Bladier** [comment]
Naapil nani sya sa OTP sir...

**Comment by cadeath** [comment]
included in version 1.2.2.6
