### ISSUE TITLE
Display PT and OR Number

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#40]
Display Pawn Ticket Number and OR Number every time the system will print

**Comment by cadeath** [comment]
Included in V1.2.0.1
For Review

**Comment by cloudNine09** [comment]
Dalton Digos2: 
INCOMPLETE

**Comment by cloudNine09** [comment]
PT# - NO DISPLAY IN NEW LOAN TRANSACTIONS ONLY IN RENEWED ITEMS

**Comment by cloudNine09** [comment]
Dalton Digos2. ADDITIONAL ISSUE:
-PREVIOUS TRANSACTIONS THAT ARE NOT YET COVERED IN ADVANCE INTEREST WHICH ARE RENEWED BY THE CUSTOMER MONTHLY, THE PRINCIPAL  AND THE NET PROCEEDS IS NOT THE SAME AND THE ITEM TYPE IN DESCRIPTION IS NOT SHOWN FOR JEWELRY IT ONLY SHOWS THE GRAMS AND KARAT..IT CONFUSES THE CUSTOMERS.

**Comment by cadeath** [comment]
Include in V1.2.0.1
Check the Version #46
