### ISSUE TITLE
Pawner Summary List PT Count didn't match

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#41]
One customer Pawning Count info didn't match
This is on the Hit Management module

Contact Maam Carol for the details

**Comment by marzxxx90** [comment]
pawn ticket count error because of multiple record

**Comment by cadeath** [comment]
Multiple record is use to get the COUNT NUMBER

**Comment by marzxxx90** [comment]
Pawn Ticket count fix, for checking

**Comment by cadeath** [comment]
Inform me if it was already checked

**Comment by cadeath** [comment]
Additional issue with #42

**Comment by cadeath** [comment]
Unsai branch ni?

**Comment by marzxxx90** [comment]
Pawner Summary sir

**Comment by cadeath** [comment]
Please read #47

**Comment by marzxxx90** [comment]
pawn ticket count error because of wrong sql query - for checking
Already update from v122
Pawner Summary Branch

**Comment by cadeath** [comment]
Good Job
To be included in Version 1.2.2

**Comment by cadeath** [comment]
Included in Version 1.2.2
