### ISSUE TITLE
Loan Renewal Montly Report - Item Total Count incorrect

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#44]
Schedule of Loan Extension and Renewals Report

Has discrepancy on the report count
Cellphone, Jewelry, Appliances don't match with the count in the Grand Total
![img_0002 copy](https://cloud.githubusercontent.com/assets/7403427/15767805/f85846ac-297d-11e6-90e2-75aabb02c854.jpg)

CREDIT to JOSE "DON2"

**Comment by cadeath** [comment]
LOGICAL ERROR OCCURRED BECAUSE ITEMTYPE BIG IS NOT ADDED IN THE APP COUNT BUT WAS ADDED IN THE GRAND TOTAL

To be included in the next version V1.2.0.2

**Comment by cadeath** [comment]
@marzxxx90 @cloudNine09 
Please double check if included in V1.2.2.9

**Comment by marzxxx90** [comment]
naa nani sa 1229 sir
