### ISSUE TITLE
Auto Patch

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#45]
Provide auto patch program that will AUTOMATICALLY install, update, or patch up new updates for the Pawnshop System

**Comment by cadeath** [comment]
Please provide GUI

**Comment by cadeath** [comment]
**Phase One - Functions**
1. Download a ZIP/RAR files from the webserver
2. Function execute Command Lines

**Comment by cadeath** [comment]
**Server-Side Functionality**
1. Selective Patching - Can select branch for the usage of the new patch
2. Bulk Patching - Send Patches to all the branches
3. Grouping - Group branches for easy selection
4. Force Patching - Close the Application for patching purposes
5. Auto Config (formerly known as Change Rate) - Can retrieve, and modify configuration
6. Schedule Patching - Schedule the effective of the Patch or Configuration
7. Unit Monitoring - Monitor the units availability including branch information

**Client-Side Functionality**
1. Can execute DOS Commands - scripting to update patches
2. Instance Checking - if the system is running or not
3. Force Close - Capable of force closing the system for updating purposes
4. Shutdown System - Can do shutdown
5. Download Zip File - capable of downloading ZIP file for patch purposes
6. Auto Config - Run configuration base on the server update
7. Schedule Execution - Set a schedule to do specific task

**Comment by cadeath** [comment]
**Server-Side Functionality**
1. Selective Patching - Can select branch for the usage of the new patch
2. Bulk Patching - Send Patches to all the branches
3. Grouping - Group branches for easy selection
4. Force Patching - Close the Application for patching purposes
5. Auto Config (formerly known as Change Rate) - Can retrieve, and modify configuration
6. Schedule Patching - Schedule the effective of the Patch or Configuration
7. Unit Monitoring - Monitor the units availability including branch information

**Client-Side Functionality**
1. Can execute DOS Commands - scripting to update patches
2. Instance Checking - if the system is running or not
3. Force Close - Capable of force closing the system for updating purposes
4. Shutdown System - Can do shutdown
5. Download Zip File - capable of downloading ZIP file for patch purposes
6. Auto Config - Run configuration base on the server update
7. Schedule Execution - Set a schedule to do specific task
8. Send client information - Sending IP, Branch Name, Version Number, etc...

**Comment by Bladier** [comment]
Check List of Partial Work
1.) Download .rar file from Web Server.
2.) Extract the .rar file, And set path to save the Extracted file.
3.) Do close the Pawnshop Application.
4.) Check if the Application is running or not.

**Comment by cadeath** [comment]
Any update?

**Comment by cadeath** [comment]
DISCONTINUE
