### ISSUE TITLE
Early Redemption v1.2

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#49]
Wrong computation for early redemption.
Due to two decimal places only save in the Interest History. It should be three (3) decimal places
eg 2.5% is 0.025, it only record 0.02

Credit to Maam Carol, Pendatun

Version 1.2

**Comment by cadeath** [comment]
Critical was added because there will be LOTS of Items that can avail early redemption

**Comment by Blade1992** [comment]
Sir I-change ba natin yung decimal places nito sa database?

**Comment by cadeath** [comment]
yup mau na ang problem

**Comment by Blade1992** [comment]
Early Redemption Interest in Table Interest History from 0.02 to 0.025
already Change.

**Comment by cadeath** [comment]
Please follow #47

**Comment by cadeath** [comment]
what branch is this

**Comment by Blade1992** [comment]
Add column in table Interest History, copy the Data Column from interest to New interest column,Delete the interest column,Rename the New interest as interest, change the position of interest.
Already updated in branch 122.
Branch Name: Early-Redemption.

**Comment by cadeath** [comment]
included in 1.2.2

**Comment by cadeath** [comment]
@cloudNine09 please update Jayr and provide a monitoring for branch database fixing
