### ISSUE TITLE
OR Sequence report - No OR

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#51]
Bug on generating OR Sequence, no OR Number

Credit: Maam Froi

**Comment by cadeath** [comment]
@cloudNine09 
@Blade1992 
@marzxxx90 
this is URGENT

**Comment by Blade1992** [comment]
Ipa ask sa namo kay emelie sir kay maam Froi kung asa ni dapit nga report.

naglakaw pa si maam Frio.

**Comment by cadeath** [comment]
Bug on generating **OR Sequence**, no OR Number
dili na nimo need si Emely, ikaw nlng icheck, naa ra sa REPORT na menu na tanan

**Comment by Blade1992** [comment]
Okey sir.

**Comment by Blade1992** [comment]
Sir okey man ang OR sequence ani sir. Kay Norman Salik nga transaction Naa man tanan OR iyng transaction sa report.

**Comment by Blade1992** [comment]
June 16 nga transaction nya sir naa man OR Number sa report.

**Comment by cadeath** [comment]
wait magTry ko

**Comment by Blade1992** [comment]
sge sir.

**Comment by cadeath** [comment]
Fixed
included in 1.2.2.2 already
