### ISSUE TITLE
Number Sequence Add OTP

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#53]
Changing each Sequence Number in frmSettings should ask for One Time Password (OTP) to the head office.

Add OTP Generator and OTP security

**Comment by cadeath** [comment]
Please add this with SAVING OTP codes and if codes was already used, use INVALID PIN error

**Comment by marzxxx90** [comment]
Saving OTP fix, embed OTP in updatesettings fix
Already Updated in 122
branch OTP

**Comment by cadeath** [comment]
Already Updated in 122?
 - Basig Updated FROM 122

**Comment by cadeath** [comment]
**For enhancement**

1. Do not ask OTP if the SYSTEM is not yet SET
2. Changing Printer should be asking OTP

**Comment by cadeath** [comment]
@marzxxx90 for revision
@cloudNine09 please note

**Comment by cadeath** [comment]
For enhancement

Do not ask OTP if the SYSTEM is not yet SET
Changing Printer should be asking OTP
add Global Variable that has switch that can turn-on and off the OTP feature

**Comment by marzxxx90** [comment]
added OTP in user management save and frmSettings
Already updated from 122
branch OTP

**Comment by cadeath** [comment]
Deployed in 1.2.2.3
