### ISSUE TITLE
Pawning Item Search

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#54]
Enhance pawning item searching
Capable of Searching Both First Name and Last Name
Fixable for searching ANY digit in Pawn Ticket Number
Able to search in Description
Has Advance Search Mechanism

**Comment by marzxxx90** [comment]
Update the sql query of pawning search
Already updated to 122
pawning search

**Comment by cadeath** [comment]
What branch?

**Comment by cadeath** [comment]
No Advance Search Feature.
Cannot search name with three (3) letters only
Searching three letters displaying zero result even if it has one (1)

**Comment by marzxxx90** [comment]
Search now allowed both firstname and lastname, error in displaying zero result fix
already update from 122
branch: pawning search

**Comment by cadeath** [comment]
removed?
any update?

**Comment by marzxxx90** [comment]
sql query change to inner join table, added radio button to filter search

**Comment by cadeath** [comment]
PLEASE UPDATE

**Comment by cadeath** [comment]
mau ba ni gahapon?

**Comment by marzxxx90** [comment]
ou sir

**Comment by cadeath** [comment]
naAu na nimo ning bug? nakaForChecking lage ni

**Comment by Blade1992** [comment]
wala pa sir.

**Comment by marzxxx90** [comment]
ok na sir na fix na nko
na merge na pud ni sa 122
brach pawning search

**Comment by cadeath** [comment]
pakiReMerge sa 1.2.2

**Comment by marzxxx90** [comment]
merge na sa 122 sir

**Comment by cadeath** [comment]
palihog ko check sa frmPawning, giguba naman nimo

**Comment by cadeath** [comment]
Please provide a CHECKLIST base from the THREAD description to insure that those listed above are done.

**Comment by marzxxx90** [comment]
Already Fix in Pawning Search:
Searching Both First Name and Last Name
Searching ANY digit in Pawn Ticket Number
Search in Description
Advance features able to search in specific item

**Comment by cadeath** [comment]
Please verify, nainclude bani sa 1.2.2.8? Please check

@marzxxx90  @cloudNine09

**Comment by marzxxx90** [comment]
naa nani sa 1229 sir..sabay ni sa OTP dati
