### ISSUE TITLE
Login Design Enhancement

### ISSUE THREAD

**Issue by Blade1992** [cadeath/Dalton#55]
Enhancement of Login Design.
Change the color combination.
For better friendly user.

**Comment by Blade1992** [comment]
Change Login Design, Change the Background, Add Icon username,and password for friendly user interface.
ALready Updated in Version 122.
Branch Name: Login Design

**Comment by cadeath** [comment]
great design
yet I won't add this to the new version.
I will refer this to other thread later for the reason
