### ISSUE TITLE
Auction Redeem Journal Entries

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#56]
**Cash In/Out - Cash In**
**Auction Redeem - Transaction names**
Sales - Jewelries		-	_SYS00000001084
Sales - Cellphones		-	_SYS00000001083
Sales - Appliances		-	_SYS00000001085
Sales - Carpentry Tools	-	_SYS00000001087
Sales - Motors/Bikes	-	_SYS00000001086

include the Motors/Bikes kay nakalimtan og butang

PS
himui lang ninyo og .cir file ni para ipakaon. kulang lang ni sa Database.

**Comment by Blade1992** [comment]
Auction Redeem Journal Entries
Create cir files, Change SAPCODE, Add Motors/Bikes in table Cash.

**Comment by cadeath** [comment]
asa naman?

**Comment by cadeath** [comment]
pakiTesting kung working ha

**Comment by marzxxx90** [comment]
Ok na sir working na..na test na nko

**Comment by marzxxx90** [comment]
sa iba na database

**Comment by Blade1992** [comment]
Na try na namo sa iban nga revolving fund...

**Comment by cadeath** [comment]
generate mog Journal Entry?

**Comment by Blade1992** [comment]
Changes: Create CIR, cir file change SAPcode in, cellphone,jewelries,carpentry tools, and add Motors?bikes. 
Already Updated in version 122.
Branch name: Auction-Redeem -Journal -Entries

**Comment by marzxxx90** [comment]
na test na pud namo ug  generate ug journal entries
