### ISSUE TITLE
Money Transfer Bracketing Report

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#57]
**Daily and Monthly Report**
All types in tblCharge will be having bracketing reports base on the amount
with the display of COUNTS, AMOUNT, CHARGES and TOTAL amount.

**Comment by cadeath** [comment]
paUrgent ko ani

**Comment by cadeath** [comment]
@marzxxx90 @cloudNine09

**Comment by marzxxx90** [comment]
new report ni sir?

**Comment by cadeath** [comment]
katong BRACKET gud...
pila ka transaction og total net ang naa sa bracket na
1-100, 101-300, 301-500, etc wala ko kabalo sa EXACT bracket pero dapat every service na naai bracket iyang iSUMMARIZE

**Comment by marzxxx90** [comment]
bracketing fix to all money transfer transaction

**Comment by cadeath** [comment]
Include the possibility to have a change rate and view previews reports

**Comment by marzxxx90** [comment]
Added Bracket Column in tblmoneytransfer
Patch Bracket Column to identify the Bracket of Transaction
Already Updated from 122
Branch Money Transfer Bracketing Report

**Comment by cadeath** [comment]
Please update on 122 for version 1.2.2.9

**Comment by marzxxx90** [comment]
Updated na ni sa 1229 sir

**Comment by cadeath** [comment]
Please follow the REPORT LAYOUT
@cloudNine09  @marzxxx90

**Comment by marzxxx90** [comment]
ok na sir

**Comment by cadeath** [comment]
To be included in V1.2.2.10
