### ISSUE TITLE
Add Monthly Report - For Auction

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#61]
1. Monthly Rematado Report
2. Monthly Jewelry - Category Rematado Report

**Comment by Bladier** [comment]
Additional: Add Monthly/Daily Report 
Already Updated version 1.2.2
Branch Name: Add Monthly Report

**Comment by Bladier** [comment]
Improve Report Design in Monthly/Daily Auction Report
Already Updated version 1.2.2
Branch Name: Add Monthly Report

**Comment by Bladier** [comment]
Add Auction Monthly Report
Updated to v 1.2.2
Branch Name: Add Monthly Report

**Comment by Bladier** [comment]
Add Form qryAuction
Add Auction MOnthly Report it can be ALL ITEMTYPE or Jewelry Only
Updated to version 1.2.2
Branch Name:Add Monthly Report

**Comment by cadeath** [comment]
**_Updated to version 1.2.2_**
Please double check...

Sync the Github before Updating from any branch

**Comment by Bladier** [comment]
Sync and Updated to version 1.2.2

**Comment by cadeath** [comment]
JWL per Category

**Comment by cadeath** [comment]
Include Auction Monthly Report in the Auction Month Report Form
Change it into Auction Monthly Transaction Report

**Comment by Bladier** [comment]
Update Monthly Auction Report
Updated to version 1.2.2

**Comment by cadeath** [comment]
NaUpdate na ni sa V1.2.2?

**Comment by Bladier** [comment]
Yes sir na Update

**Comment by cadeath** [comment]
pakiFix imong grammar sa imong giPost ha.
Updated to version 1.2.2 <-- murag mali ni

#47 pkicheck ni

**Comment by cadeath** [comment]
DONE
Renamed report names

INCLUDED in V1.2.2.4

**Comment by cadeath** [comment]
Please verify if included na sa v1.2.2.9
@marzxxx90 @cloudNine09

**Comment by marzxxx90** [comment]
naa nani sa 1229 sir

**Comment by Bladier** [comment]
UPDATE TO 1.2.2.10
