### ISSUE TITLE
Backup Module

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#63]
To regenerate **backup.bat** which include a PASSWORD on the script.
Backup Module requires Backup Path and a button that will reconfig the backup.bat

**Comment by cadeath** [comment]
password will be discuss later. place a sample password temporarily

**Comment by cadeath** [comment]
@cloudNine09 please make this urgent and tell jayr na iAccept ang invitation sa GITHUB sa iyang EMAIL

**Comment by marzxxx90** [comment]
Added form frmBackupData
Created friendly User Interface for backup.bat
For user to easy set the setting without manually opening or editing the backup.bat
The backup data protected by password
Already updated from 122
Branch Backup Module

**Comment by cadeath** [comment]
included in 1.2.2.8

**Comment by cadeath** [comment]
Please check
Murag wala gaCompress ang RAR
ang size daku kaayo

please post the command you are using here

**Comment by cadeath** [comment]
@marzxxx90 @cloudNine09

**Comment by marzxxx90** [comment]
Ok na sir na fix na nko

 sw.WriteLine("@echo off")
            sw.WriteLine("title cdt-S0ft - MANUAL BACKUP")
            sw.WriteLine("echo PLEASE CLOSE THE PAWNSHOP SYSTEM")
            sw.WriteLine("pause")
            sw.WriteLine("echo PLEASE WAIT WHILE SYSTEM IS BACKING UP")
            sw.WriteLine("rar a " & txtPath2.Text & "\" & mod_system.BranchCode & ".rar -agMMddyyyy W3W1LH4CKU.FDB -hp" _
                         & BranchCode & "MIS") 'Password = MISJUNMAR(uppercase)
            sw.WriteLine("cls ")
            sw.WriteLine("echo DONE!!! THANK YOU FOR WAITING")
            sw.WriteLine("pause")
            sw.WriteLine("exit")

**Comment by marzxxx90** [comment]
Updated nani sa 1229 sir
Branch: Backup Module

**Comment by cadeath** [comment]
Please verify
makaCOMPRESS ba ni?

**Comment by marzxxx90** [comment]
ou sir

**Comment by cadeath** [comment]
To be included in 1.2.2.10

**Comment by marzxxx90** [comment]
Allow to backup compliance picture files

**Comment by marzxxx90** [comment]
Backup Module updated, added compliance file to backup

**Comment by marzxxx90** [comment]
Waiting for Compliance filename to be use in backup
