### ISSUE TITLE
Pawning Report

### ISSUE THREAD

**Issue by Bladier** [cadeath/Dalton#64]
Failed to load Pawn Information.
Pawnticket conversion to string from int is not valid.

**Comment by cadeath** [comment]
Unsai update ani?

**Comment by Bladier** [comment]
wala pa ,, kuhaon sa nako ang database ani, date sir.

**Comment by cadeath** [comment]
unsai update?

**Comment by Bladier** [comment]
Katong sa Report Sir kung mag Open ug isa ka report,tapos mag open pod isa ka report mag error sya.
Dapat kung mag generate ug report sir. i close sa to ang isa form viewer una mag report ug usab...
