### ISSUE TITLE
Report - Month Renewal Break Down

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#66]
Categories Renewal Report per Item Type (MONTHLY)

**Comment by Bladier** [comment]
Additional: Add RenewalBreakDown Report
Updated from VERSION 1.2.2.5
BranchName:Report - Month Renewal Break Down

**Comment by cadeath** [comment]
Please check your work

**Comment by cadeath** [comment]
Renewal will be base on OR date, it means STATUS = 'R' don't have OR date.
It will not be listed in the report. Please be advice

@Bladier @cloudNine09

**Comment by Bladier** [comment]
Additional: Add RenewalBreakDown Report
Changes: Change from Loandate to ORdate parameter
Updated from VERSION 1.2.2.5
BranchName:Report - Month Renewal Break Down

**Comment by cadeath** [comment]
naInclude ba ni sa 1.2.2.8?
Please double check

**Comment by cadeath** [comment]
@cloudNine09  paFollowup

**Comment by cadeath** [comment]
Please update using 122 for version 1.2.2.9

**Comment by Bladier** [comment]
Na update na sa 1.2.2.9 ,sir. sabay ni sa OTP sir

**Comment by cadeath** [comment]
Please update me on this

**Comment by Bladier** [comment]
OKey na ni sir. na update na ni sa 1.2.2.9

**Comment by cadeath** [comment]
pakiCheck if naDeploy ni

**Comment by Bladier** [comment]
Included in version 1.2.2.9 .
Deployed already.

**Comment by Bladier** [comment]
Mao ni ang  Gidungag nako 
Additional: Add RenewalBreakDown Report
Changes: Change from Loandate to ORdate parameter
BranchName:Report - Month Renewal Break Down
Included in version 1.2.2.9 .
Deployed already.

**Comment by Bladier** [comment]
Changes in report: 'Segregated list' to 'AUCTION MONTHLY REPORT' label.

**Comment by cadeath** [comment]
Any update?

**Comment by Bladier** [comment]
OKEY NA NI SIR.. UPDATED NA NI SA  1.2.2.12.
