### ISSUE TITLE
Data Extraction

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#67]
Extract all transaction in a monthly basis
Extracted data will be save in EXCEL FILE
All extracted data will be compress and place a password

Provide Sir Dennis all the EXTRACTED RAW FILE in an EXCEL FORMAT for a specific month for his perusal.
Extracted data will be reconstructed in a ACCOUNTING READABLE data.

**Comment by Bladier** [comment]
Additional: Add form ExtractDataFromDatabase
Content: Extract data from database specifically in table Pawning, Dollar, Moneytransfer,Insurance, Borrowing.
Branchname: Views
Updated from V1.2.2.8
Compressed to .rar with password not finished . . .

**Comment by Bladier** [comment]
UPDATE: Compressing with password is okey.. 
BranchName: Views
updated from V1.2.2.8
Tested Extracted data

**Comment by cadeath** [comment]
Please update to 122
for version 1.2.2.9

**Comment by Bladier** [comment]
Already Updated from version 1.2.2.9
BranchName: Views

**Comment by Bladier** [comment]
Finished in checking Errors.

**Comment by cadeath** [comment]
Unsai problem?

**Comment by Bladier** [comment]
Katong sa pag read extract.bat sir... okey man diri sir.

**Comment by cadeath** [comment]
why sa akoa dili?

**Comment by Bladier** [comment]
kailangan sir buhaton na ug installer para matry kung working sya.. 
kay sa Drive D: man gud na iyang default nga ginakuhaan ug Extract.bat sir.

**Comment by cadeath** [comment]
pwde imong iDynamic? gamita ang TEMPORARY FILE kay READ/WRITE na xa compare sa DRIVE D:

**Comment by cadeath** [comment]
any update? na Fix na ang problem?

**Comment by Bladier** [comment]
oo sir katong sa Iyang status Change to Letter to Word L to New Loan, R to redeem ,W Withdraw etc.

**Comment by Bladier** [comment]
add: BranchName to Excel file
updated from 1.2.2.10

**Comment by cadeath** [comment]
Answer "all" TODO before putting FOR CHECKING here

**Comment by cadeath** [comment]
ANY UPDATE?

@marzxxx90  @cloudNine09

**Comment by marzxxx90** [comment]
na check na nko ang extraction sir..maka extract na pud siya ug cash in / out

**Comment by cadeath** [comment]
please update from MASTER

**Comment by Bladier** [comment]
BranchName: Views
updated from Master
Tested Extracted data

**Comment by cadeath** [comment]
Included in 1.2.3.6
