### ISSUE TITLE
Borrowing In

### ISSUE THREAD

**Issue by cloudNine09** [cadeath/Dalton#69]
Dalton Roxas 
July 24, 2016
Overage of 80,000, borrowing in not appear on Daily Cash Count.
July 25, 2016
Borrowing In not appear on their daily cash count.
Overage of 60,000
@Bladier

**Comment by cadeath** [comment]
Please provide us other information like Branch, Date, Description, etc

**Comment by cadeath** [comment]
@Bladier @marzxxx90 
Please double check if naInclude naba ni sa 1.2.2.9

**Comment by Bladier** [comment]
asa ge mean nimo nga i change ang Borrowing to Borrowing In sir kaning sa form nya sir?

**Comment by Bladier** [comment]
Nainclude nani sa 1.2.2.9 sir...

**Comment by Bladier** [comment]
Sir wla ni naapil sa 1.2.2.9.
Bag o lng ni naa update sa 1.2.2.9

**Comment by cadeath** [comment]
unsa? wala na apil sa 1.2.2.9 pero bag o lang ni naa update sa 1.2.2.9?

**Comment by Bladier** [comment]
Na Update na di na sir na include nani sa 1.2.29, ganina , kay naapil man di sa journal sa sir nga pag update ni journal..

**Comment by Bladier** [comment]
ge double check napod nako ang 1.2.2.9 sir. na include nani ddto.

**Comment by cadeath** [comment]
Included in 1.2.2.9
