### ISSUE TITLE
Remove Principal from Report

### ISSUE THREAD

**Issue by marzxxx90** [cadeath/Dalton#70]
Remove Principal Value from:
1.Outstanding Report
2.Pullout list Report
3.Segregate list Report

**Comment by marzxxx90** [comment]
Only Have Privilege Can View The Value of Principal

**Comment by marzxxx90** [comment]
Update:
Remove Principal Value if user don't have privilege
Already Updated from 122
Branch: Remove grand total in report

**Comment by cadeath** [comment]
CHECKED with MINOR problem
Please revise on USER MANAGEMENT
 - ask everything before OTP
 - by default REPORTS are UNCHECKED except ALL 1 users (Super Admin and PDuNxp8S9q0=)
 - updating PRIVILEGE to a user requires only ONE(1) password

**Comment by marzxxx90** [comment]
ma unchecked na nko ang reports sir

**Comment by cadeath** [comment]
@marzxxx90 @cloudNine09 
URGENT

**Comment by marzxxx90** [comment]
na fix na nko 2ng mag zero ang privilege 
Updated napud ni sa 122
Branch: remove grand total in report

**Comment by cadeath** [comment]
Included in 1.2.2.9

**Comment by marzxxx90** [comment]
Added Audit Report Privilege...Only User have Audit Report Privilege can view the principaland Grand Total of Report
