### ISSUE TITLE
VOID REPORT

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#71]
Add Table recording every VOID.
Add Fields
- Reason
- Transaction Module
- Encoder
- Voided by

**Comment by marzxxx90** [comment]
Daily ug Monthly ni sir?

**Comment by cadeath** [comment]
Both
Atoang iReStructuring ang report later... samok naman gud :P

**Comment by marzxxx90** [comment]
cge sir..naa nkoy flowchart ani sir

**Comment by cadeath** [comment]
Wala paka kaStart ani noh?

**Comment by marzxxx90** [comment]
nagstart na sir

**Comment by marzxxx90** [comment]
Added:
function for saving voided transaction
Daily & Monthly Void Reports
Already Updated from 122
Branch: Void Report

**Comment by cadeath** [comment]
dili na 122, please update on "master"

**Comment by marzxxx90** [comment]
Updated nani sa master sir

**Comment by cadeath** [comment]
@cloudNine09 please provide me some branches that has void transactions to test this thread

**Comment by cadeath** [comment]
Checked in 1.4-POS
DONE
