### ISSUE TITLE
Borrowing

### ISSUE THREAD

**Issue by cloudNine09** [cadeath/Dalton#72]
Borrowing in/out form makaconfuse sya sa user.  dapat nakalagay ang specific title ng form para malaman ka ng user if Borrowing in ba or out yon na form. Tpos yung BROWSE na button dapat may specific yun xa na name for borrowingIN. If ganun na talaga ang FORM for Borrowing dapat my user guide na nakalagay dun sa HELP if paano mg transact sa BORROWING.

**Comment by marzxxx90** [comment]
Enhance Branch To Branch Gui to be more Friendly User Interface ..Added Tab Control to easy identify if borrow out or in
Already Updated from 122
Branch:BranchToBranchNewGui

**Comment by cadeath** [comment]
INCLUDED in version 1.2.2.15
