### ISSUE TITLE
Base on Incident Report # 027: Pawning Error in Redemption

### ISSUE THREAD

**Issue by marzxxx90** [cadeath/Dalton#75]
Error in Pawning Redemption Because Of Clicking New Loans Button while Pawning Item is Open

**Comment by marzxxx90** [comment]
Added Notification for Pawn Item for every clicking in btnloan, btnrenew, btnredem while pawn item already open
Already Updated from master
Branch: Pawning Bug

**Comment by cadeath** [comment]
Included in 1.2.3.6
