### ISSUE TITLE
Journal Entries

### ISSUE THREAD

**Issue by Arskie** [cadeath/Dalton#78]
1. Pag mag Addfund dapat dili na mo gawas sa journal entries. (Cash in/out --> FUND REPLENISHMENT)
2. Debit Credit sa journal entries my mga time na naga tapad. na update na daw sa 1231. to be check kng naah gihapon or wala na

**Comment by marzxxx90** [comment]
Gi Update lng nko ang sql query para dli mag gawas ang add fund sa journal entry
Ang Debit Credit na issue na fix na..nag add lng q ug Early Redemption sa Transtype para ma separate ang iyang Debit ug Credit
Already Updated From Master
Branch: Journal

**Comment by marzxxx90** [comment]
Included in Issue #13
