### ISSUE TITLE
testing 1.2.3.6

### ISSUE THREAD

**Issue by Arskie** [cadeath/Dalton#80]
1. User Management
Deactivate Account: check enable/disable user --> Pag naka check ang check box maka log in lang japon.
                                                                           --> Pag wala naka check ang check box maka log in japon.
2. Pawning Void: Pag mag void sa new loan makita japon sa report, sa loan register.
3. Branch to Branch: Pag mag void makita japon sa Report ang record.

**Comment by marzxxx90** [comment]
Nag Add lng q ug trap para sa mga Void na transaction ug Deactivate na account
Updated nani sa Master
Branch: User Management (Gi isa nlng nko dre)

**Comment by cadeath** [comment]
Unsa ni?
