### ISSUE TITLE
Daily Report

### ISSUE THREAD

**Issue by cloudNine09** [cadeath/Dalton#81]
Branch: KABACAN
Incident: The amount of P17,600 missing from the Monthly but existed in the Daily. It was found out that this incident was recorded as IR-2016-048 in the MIS Department, stated that Marco Akmad, Pawner, changed his mind in pawning his Bracelet. This was VOIDED and found out a BUG* on their report viewer in DAILY BASES didn't filter VOID and reflected on Loan Register for New Loan but not in MONTHLY.

**Comment by cadeath** [comment]
@jayr @marzxxx90 please verify
