### ISSUE TITLE
Table Pawning Item 

### ISSUE THREAD

**Issue by Bladier** [cadeath/Dalton#90]
Add ItemID 
add InterestRate

**Comment by cadeath** [comment]
Why need pa InterestRate? nagaRecord bata ani?

@Bladier  @cloudNine09  @marzxxx90

**Comment by cadeath** [comment]
Table OPI (PawnItem) don't need ItemID and InterestRate


OPT (PawnTicket) needs PawnItemID from OPI

InterestRate is the INTEREST SCHEME from OPT and be referred in TBLINTSCHEMES

**Comment by cadeath** [comment]
Please confirm and verify

@marzxxx90 @Bladier @cloudNine09 
and Close this issue
