### ISSUE TITLE
Pawning Module for version 1.3

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#94]
UPDATE
 [+] Console module in already included

All development in the NEW pawning module for version 1.3 should be monitored here.
For any update that requires detailed monitoring will be created a different thread BUT must be referred here

[+] Can New Loan
[+] Can Renew
[+] Can Redeem
[+] Add DescriptionBuilder
[+] Add Description on OPT

[-] No Report
[-] No Print/RePrint
[-] No viewing
[-] Button is not yet working properly
[-] Claimer isn't fix yet

Please be advice.
Include other unfinish bugs here.

**Comment by marzxxx90** [comment]
Views fields for Printing Pawning:
PAWNID
PAWNTICKET
LOANDATE
MATUDATE
EXPIRYDATE
AUCTIONDATE
ITEMCATEGORY
PAWNER
FULLADDRESS
CONTACTNUMBER
PRINCIPAL
APPRAISAL
INTEREST
ADVINT
PENALTY
SERCECHARGE
NETAMOUNT
DESCRIPTION
ORNUM
ORDATE
RENEWDUE
REDEEMDUE

**Comment by marzxxx90** [comment]
PawnID
Interest
Advint
ServiceCharge
Netamount
ContactNumber

**Comment by cadeath** [comment]
PAWN_LIST is now updated
Interest = DelayInterest

**Comment by cadeath** [comment]
Please verify
OK na ang ADMIN PANEL for
 - Item Classification
 - Interest Scheme

**Comment by marzxxx90** [comment]
Ok na sir.. maka Add, Update ug View na ug Item with Specification apil na dre ang Scheme

**Comment by cadeath** [comment]
pakiInclude ang branch para kabalo ko asa nq kuhaon...

**Comment by marzxxx90** [comment]
Branch: AdminPanelGui

**Comment by marzxxx90** [comment]
Wala lge PawnID dre sa Pawn_list na View sir

**Comment by marzxxx90** [comment]
wla gagana ang Over Due days, Penalty, Renew Due ug ang Redeem Due..1 month lng ang gina calculate sa Renew ug Redeem Due

**Comment by cadeath** [comment]
Please sync

I already fixed it in the Pawning Module
I changed txtMatu into PT_Entry.Maturity

**Comment by cadeath** [comment]
Error on Admin Module #96

**Comment by marzxxx90** [comment]
Pullout Date view need in Report

**Comment by cadeath** [comment]
TO BE INCLUDED
- Withdraw Date (Pullout - Obsolete)
- Update Withdraw Date and Status from OPI
