### ISSUE TITLE
Printing Name in PT

### ISSUE THREAD

**Issue by marzxxx90** [cadeath/Dalton#95]
Clarification the Name of Pawn Ticket if Pawner name or Claimer Name to be printed

**Comment by cadeath** [comment]
As per interview, 
NO HARD DOCUMENT
Pawner's name is listed in the PawnTicket (Roxas)

Please verify

**Comment by cadeath** [comment]
As per meeting,

Memo will be release soon about NON-PAWNTICKET owner.
It was discussed that it will be the ORIGINAL PAWNER'S NAME will be listed in the PAWNTICKET and the claimer will be recorded.

Please finalize
