### ISSUE TITLE
Admin Module

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#96]
SEARCHING
- Empty String means display EVERYTHING

SAVING/UPDATING
- in UPDATING, include INTEREST SCHEME
- Button should be; SAVE, EDIT, CLOSE. when clicking EDIT; UPDATE, CANCEL, CLOSE

**Comment by marzxxx90** [comment]
Searching even empty string Fix
Updating Interest Scheme Bug Fix
Buttons Bug Fix
Branch: AdminPanelGui

**Comment by cadeath** [comment]
-Console Must have OTP
-Search Class display editable classification, category, description, and print layout
-Edit Class; Clicking Cancel, Classification Information should not be CLEARED but Interest scheme remains.
-Remove time
-Remove Maximize button

**Comment by marzxxx90** [comment]
Edit Class Fix
Time Remove
Form Maximize Button Remove
Branch: AdminPanelGui

**Comment by cadeath** [comment]
When cancel, all modified fields did not reset.
I clicked edit and modify the Print Layout ([K:ENC]), but when I canceled it and clicked YES, the modified Print Layout remain on the display.

**Comment by marzxxx90** [comment]
Added Load_ItemSpecification function to reload selected item if cancel

**Comment by marzxxx90** [comment]
Added Load_ItemSpecification function to reload selected item if cancel

**Comment by marzxxx90** [comment]
included in #94
