### ISSUE TITLE
Exporting PDF on Outstanding Report: Pawn Ticket No. Issue

### ISSUE THREAD

**Issue by cloudNine09** [cadeath/Dalton#97]
Branch: Gaisano Polomolok
Exporting PDF Outstanding report for month of March in Pawnshop System sees that the Pawn ticket Number stated  6 ZERO digits not the exact Pawn ticket No.

**Comment by marzxxx90** [comment]
Pawnticket Zero if Item Status Renewed

**Comment by marzxxx90** [comment]
Remove trim in expresion (=IIF(Fields!Status.Value.ToString.trim= "RENEWED",Fields!OldTicket.Value ,Fields!PawnTicket.Value)) to display pawnticket if status value Renewed
